
version: '3'
services:

  postgres:
      image: postgres
      container_name: golang_postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=password
      ports:
        - 5432:5432