// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"fmt"
	"time"
)

type Oderenum string

const (
	OderenumPending Oderenum = "pending"
	OderenumProcess Oderenum = "process"
	OderenumDone    Oderenum = "done"
)

func (e *Oderenum) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Oderenum(s)
	case string:
		*e = Oderenum(s)
	default:
		return fmt.Errorf("unsupported scan type for Oderenum: %T", src)
	}
	return nil
}

type Role string

const (
	RoleAdmin    Role = "admin"
	RoleCustomer Role = "customer"
)

func (e *Role) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Role(s)
	case string:
		*e = Role(s)
	default:
		return fmt.Errorf("unsupported scan type for Role: %T", src)
	}
	return nil
}

type Book struct {
	ID             int32     `json:"id"`
	Name           string    `json:"name"`
	Price          int32     `json:"price"`
	Quantity       int32     `json:"quantity"`
	Image          string    `json:"image"`
	Description    string    `json:"description"`
	BookCategoryID int32     `json:"book_category_id"`
	CreatedAt      time.Time `json:"created_at"`
}

type BookCategory struct {
	ID        int32     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Order struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	Status    Oderenum  `json:"status"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type OrderItem struct {
	OrderID      int32     `json:"order_id"`
	BookID       int32     `json:"book_id"`
	Quantity     int32     `json:"quantity"`
	PriceInvoice int32     `json:"price_invoice"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	ID        int32     `json:"id"`
	Username  string    `json:"username"`
	Password  string    `json:"password"`
	Email     string    `json:"email"`
	Role      Role      `json:"role"`
	FullName  string    `json:"full_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
